### PR TITLE
support for generating additional client certs

### PR DESCRIPTION
**Pull request by mihaj**
@lukebakken please check it out.

### CODE REVIEW

**Comment by mihaj** [comment]
closes #18

**Review by lukebakken — CHANGES_REQUESTED** [review]
Please do not remove the MPL license header.

**Comment by mihaj** [comment]
Ups, I've put it back.

**Comment by michaelklishin** [comment]
It's an interesting feature, will take a look soon.

**Comment by johnvanham** [comment]
@mihaj Just tried your fork as I want to generate additional client certs as I need 3 clients to talk to a RabbitMQ server but I can't generate the initial certs as it returns the following error:

```
jvh@jvh-laptop-lin:~/tls-gen/basic$ make PASSWORD=bunnies
python3 profile.py regenerate --password "bunnies" \
--common-name jvh-laptop-lin \
--client-alt-name jvh-laptop-lin \
--server-alt-name jvh-laptop-lin \
--days-of-validity 3650 \
--key-bits 2048 
Traceback (most recent call last):
  File "/home/jvh/tls-gen/basic/profile.py", line 93, in <module>
    cli.run(commands)
  File "/home/jvh/tls-gen/basic/../tls_gen/cli.py", line 71, in run
    dispatch_command(commands, parser, args, options)
  File "/home/jvh/tls-gen/basic/../tls_gen/cli.py", line 45, in dispatch_command
    fn(options)
  File "/home/jvh/tls-gen/basic/profile.py", line 56, in regenerate
    clean(opts)
  File "/home/jvh/tls-gen/basic/profile.py", line 47, in clean
    paths.leaf_pair_path('server'.format(cn)),
NameError: name 'cn' is not defined
make: *** [../common.mk:74: regen] Error 1
```
I've tried with CN= and cn= also but same error.

**Comment by mihaj** [comment]
@johnvanham you need to specify the command. In your case you probably want to use `gen-client` command like this:

```powershell
 make gen-client PASSWORD=bunnies
```

**Comment by johnvanham** [comment]
> @johnvanham you need to specify the command. In your case you probably want to use `gen-client` command like this:
> 
> ```powershell
>  make gen-client PASSWORD=bunnies
> ```

How do you generate CA and server certs as well?

**Comment by mihaj** [comment]
@johnvanham

If you want to generate client certificates (with `gen-client`), you first need CA and server certificates. Then you can generate additional client certificates. So first you need to:

1. Make sure that /basic folder is empty
2. Run the generator for example: `make gen USE_ECC=true DAYS_OF_VALIDITY=365 CN=guest PASSWORD=bunnies`. That will generate CA certificate, server certificate, and client certificate for (guest user). If you want to use different CN, specify it in the command above. Also look into setting SERVER_ALT_NAME property, to add the server hostname or IP address.
3. Then you can make additional client certificates from the certs in step 2 for example: `make gen-client USE_ECC=true DAYS_OF_VALIDITY=365 CN=aternativeclient PASSWORD=bunnies`

**Comment by johnvanham** [comment]
@mihaj Great, that works!

So does the documentation need to be updated? Both https://github.com/mihaj/tls-gen/blob/133dc2eb2652e0ba1bc5c034cdcd078c0acd89c1/README.md and https://github.com/mihaj/tls-gen/blob/133dc2eb2652e0ba1bc5c034cdcd078c0acd89c1/basic/README.md say to use:

```make PASSWORD=bunnies```

But this no longer works without using ```gen```

I also noticed that..

```make info``` does not work. But ```make verify``` does work.

Thanks for the update to generate multiple client certs! :smiley:

**Comment by michaelklishin** [comment]
Closed due to inactivity.

**Comment by lukebakken** [comment]
See #37

**Pull request closed without merging**
